### ISSUE TITLE
To Merge:

### ISSUE THREAD

**Issue by rushilsrivastava** [ClearVoid/2017FRC2854#2]
Drive --> Visual

Visual --> Master

They are both behind approx. 2 revision

**Comment by CoffeeVector** [comment]
We're only going to merge when we need to. Palani and does not see this as a issue, nor do I see this as an issue at all. As you can tell, the branches are mostly editing different parts of the project, so being out of step does not affect workflow.

**Comment by rushilsrivastava** [comment]
My bad, I thought we were going to do a test run this Friday (Rasp Pi). I have started documentation, I will mark this as resolved.
